/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RestAssuredTest;

//import org.junit.Test;

import io.restassured.response.Response;

import static io.restassured.RestAssured.given;
import static org.junit.Assert.*;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

import org.testng.Assert;
import org.testng.annotations.Test;



public class TestCases {
	
	@Test(description = "Rest Assured Test")
    public void getMethodExample1() {
        
        Response res=given().when().get("https://reqres.in/api/users/2");
        System.out.println("GET call response:"+res.getBody().asString());
    }
	
	@Test(description = "Rest Assured GET test 2")
	 public void getMethodExample2() {
	        
	        Response res=given().when().get("https://reqres.in/api/unknown");
	        System.out.println("New GET call response:"+res.getBody().asString());
	        Assert.assertEquals(res.getStatusCode(), 200);
	    }
	
	@Test(description = "GET URL path value")
	 public void getMethodExample3() {
        
        Response res=given().when().get("https://reqres.in/api/users/2");
        System.out.println("URL path value from GET call: "+res.getBody().jsonPath().getString("support.url"));
//        Assert.assertEquals(res.getStatusCode(), 200);
    }
	
	@Test(description = "POST method")
	public void postMethodExample1() {
		Response res=given().header("Content-Type", "Application/JSON").body("{\r\n    \"name\": \"morpheus\",\r\n    \"job\": \"leader\"\r\n}").post("https://reqres.in/api/users");
		System.out.println("POST call response:"+res.getBody().prettyPrint());
	}
	
	@Test(description = "POST method with external JSON payload")
	public void postMethodExample2() throws Exception {
				
		String file = System.getProperty("user.dir")+"/src/test/resources/jsonPayloads/UserCreate.json";
        String request_json = new String(Files.readAllBytes(Paths.get(file)));
        System.out.println("Request body passed for POST: "+request_json);
		
		Response res=given().header("Content-Type", "Application/JSON").body(request_json).post("https://reqres.in/api/users");
		Assert.assertEquals(res.getStatusCode(), 201);
		System.out.println("POST call response:"+res.getBody().asString());
	}
	
	@Test(description = "PUT method call with external JSON payload")
	public void putMethodExample1() throws Exception {
				
		String file = System.getProperty("user.dir")+"/src/test/resources/jsonPayloads/UpdateUser.json";
        String request_json = new String(Files.readAllBytes(Paths.get(file)));
        System.out.println("Request body passed for PUT: "+request_json);
		
		Response res=given().header("Content-Type", "Application/JSON").body(request_json).put("https://reqres.in/api/users/2");
		Assert.assertEquals(res.getStatusCode(), 200);
		System.out.println("PUT call response:"+res.getBody().asString());
	}
	
	@Test(description = "DELETE method call")
	public void deleteMethodExample1() throws Exception {
		
		Response res=given().header("Content-Type", "Application/JSON").delete("https://reqres.in/api/users/2");
		Assert.assertEquals(res.getStatusCode(), 204);
		//System.out.println("DELETE call response:"+res.getBody().asString());
	}
	
	}
	

